USE [master]
GO

/****** Object:  Database [PerformanceTracker]    Script Date: 12/01/2022 00:17:31 ******/
CREATE DATABASE [PerformanceTracker]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PerformanceTracker', FILENAME = N'C:\Users\m.erkan\PerformanceTracker.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PerformanceTracker_log', FILENAME = N'C:\Users\m.erkan\PerformanceTracker_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PerformanceTracker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PerformanceTracker] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PerformanceTracker] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PerformanceTracker] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PerformanceTracker] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PerformanceTracker] SET ARITHABORT OFF 
GO

ALTER DATABASE [PerformanceTracker] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PerformanceTracker] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PerformanceTracker] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PerformanceTracker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PerformanceTracker] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PerformanceTracker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PerformanceTracker] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PerformanceTracker] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PerformanceTracker] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PerformanceTracker] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PerformanceTracker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PerformanceTracker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PerformanceTracker] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PerformanceTracker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PerformanceTracker] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PerformanceTracker] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PerformanceTracker] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PerformanceTracker] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PerformanceTracker] SET  MULTI_USER 
GO

ALTER DATABASE [PerformanceTracker] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PerformanceTracker] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PerformanceTracker] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PerformanceTracker] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PerformanceTracker] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PerformanceTracker] SET QUERY_STORE = OFF
GO

USE [PerformanceTracker]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [PerformanceTracker] SET  READ_WRITE 
GO

